name: geospatial_data_science
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6    # Python version 3.6
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - geopandas     # Geospatial extension of pandas
    - h5py          # Wrapper for HDF5
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for NetCDF4
    - notebook      # Notebook interface
    - numpy         # N-d array and numerics 
    - pandas        # Labeled data analysis
    - pyresample    # Geographic resampling tools
    - rasterio      # Access to geospatial raster data
    - scipy         # Common math/stats/science functions
    - scikit-learn  # Macine learning library
    - scikit-image  # Image processing
    - spyder        # Scientific development environment
    - statsmodels   # Regression/modeling toolkit
    - seaborn       # Statistical visualizations
    - xarray        # N-d labeled array library
